#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
STATIC_DIR="$SCRIPT_DIR/../static"
EMSDK_DIR="${EMSDK:-${EMSDK_DIR:-$HOME/emsdk}}"

# Skip if output already exists (delete static/letterpress_wasm.js to force a rebuild)
if [ -f "$STATIC_DIR/letterpress_wasm.js" ]; then
    echo "static/letterpress_wasm.js already present; skipping build. Delete it to rebuild."
    exit 0
fi

# Activate emsdk if available
if [ -f "$EMSDK_DIR/emsdk_env.sh" ]; then
    # shellcheck source=/dev/null
    source "$EMSDK_DIR/emsdk_env.sh"
fi

if [ ! -d "$BUILD_DIR" ]; then
    echo "Build directory not found. Running setup first..."
    "$SCRIPT_DIR/setup.sh"
fi

echo "Building WASM target..."
cmake --build "$BUILD_DIR" --target letterpress_wasm

echo "Copying WASM files to static/..."
mkdir -p "$STATIC_DIR"
cp "$BUILD_DIR/letterpress_wasm.js" "$STATIC_DIR/"
cp "$BUILD_DIR/letterpress_wasm.wasm" "$STATIC_DIR/"
# Copy preloaded data file if present (generated by --preload-file in CMakeLists)
if [ -f "$BUILD_DIR/letterpress_wasm.data" ]; then
    cp "$BUILD_DIR/letterpress_wasm.data" "$STATIC_DIR/"
fi

echo "Done."
